STATIC_UI_KB = {
    "tiktok": {
            "like":    {"pos": [(0.935, 0.42)], "desc": "heart on right sidebar"},
        "comment": {"pos": [(0.935, 0.52)], "desc": "comment bubble on right sidebar"},
        "share":   {"pos": [(0.935, 0.61)], "desc": "curved share arrow on right sidebar"},
        "mute":    {"pos": [(0.935, 0.71)], "desc": "speaker icon at lower right"},
        "close":   {"pos": [(0.965, 0.06), (0.035, 0.06), (0.50, 0.83)], "desc": "popup close (X/cancel) corners or center-bottom"},
        "home":   {"pos": [(0.1, 0.91)], "desc": "home button on the navigation bar where the video feed is"},
        "search":   {"pos": [(0.3, 0.91)], "desc": "magnifying button on the navigation bar to find videos by searching"},
        "upload":   {"pos": [(0.5, 0.91)], "desc": "a plus button on the navigation bar to upload a video"},
        "inbox":   {"pos": [(0.7, 0.91)], "desc": "box button on the navigation bar to check the messages from or text friends"},
        "profile":   {"pos": [(0.9, 0.91)], "desc": "a person button on the navigation bar to visit profile page of the user."},
        "send": {"pos": [(0.91, 0.93)], "desc": "send button, right-pointing triangle"},
        "submit": {"pos": [(0.91, 0.93)], "desc": "send button, right-pointing triangle"},
        "text_field": {"pos": [(0.50, 0.92)], "desc": "comment text field input area"},
        },

    "instagram": {
        "comment": {"pos": [(0.20, 0.88), (0.50, 0.90)], "desc": "bubble below post or Reels rail"},
        "like":    {"pos": [(0.12, 0.88)], "desc": "heart below post / right rail on Reels"},
        "share":   {"pos": [(0.28, 0.88)], "desc": "paper plane below post"},
        "profile": {"pos": [(0.90, 0.92)], "desc": "profile tab on bottom nav (right)"},
        "close":   {"pos": [(0.96, 0.06), (0.04, 0.06), (0.50, 0.82)], "desc": "popup close"},
    },
    "youtube_shorts": {
        "like":       {"pos": [(0.92, 0.45)], "desc": "thumbs-up on right sidebar"},
        "comments":   {"pos": [(0.92, 0.58)], "desc": "speech bubble on right sidebar"},
        "share":      {"pos": [(0.92, 0.70)], "desc": "share arrow on right sidebar"},
        "channel":    {"pos": [(0.92, 0.32)], "desc": "channel avatar above action stack"},
        "subscribe":  {"pos": [(0.20, 0.86)], "desc": "Subscribe pill near lower-left"},
        "close":      {"pos": [(0.96, 0.06), (0.04, 0.06), (0.50, 0.82)], "desc": "close overlays (X/back/‘Got it’)"},
    },
    "facebook_reels": {
        "like":     {"pos": [(0.92, 0.45)], "desc": "like on right sidebar"},
        "comment":  {"pos": [(0.92, 0.58)], "desc": "comment bubble on right sidebar"},
        "share":    {"pos": [(0.92, 0.70)], "desc": "share arrow on right sidebar"},
        "profile":  {"pos": [(0.92, 0.32)], "desc": "creator avatar above actions"},
        "follow":   {"pos": [(0.18, 0.86)], "desc": "Follow pill near lower-left"},
        "close":    {"pos": [(0.96, 0.06), (0.04, 0.06), (0.50, 0.82)], "desc": "dismiss popups/‘Not now’"},
    },
    "x": {  # Twitter/X tweet view
        "reply":    {"pos": [(0.20, 0.92)], "desc": "reply icon on bottom action row"},
        "retweet":  {"pos": [(0.42, 0.92)], "desc": "retweet on bottom action row"},
        "like":     {"pos": [(0.64, 0.92)], "desc": "heart on bottom action row"},
        "share":    {"pos": [(0.86, 0.92)], "desc": "share icon on bottom action row"},
        "profile":  {"pos": [(0.09, 0.09)], "desc": "profile/avatar top-left area"},
        "close":    {"pos": [(0.04, 0.06), (0.96, 0.06)], "desc": "close modals/dialogs (top corners)"},
    },
}
